using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Brovan.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class StructSerializerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structs = context.SyntaxProvider.CreateSyntaxProvider(IsStructCandidate, GetStructSymbol);
            var combined = context.CompilationProvider.Combine(structs.Collect());
            context.RegisterSourceOutput(combined, Execute);
        }

        private static bool IsStructCandidate(SyntaxNode node, CancellationToken ct)
        {
            return node is StructDeclarationSyntax s && s.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetStructSymbol(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            return ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        }

        private static void Execute(SourceProductionContext ctx, (Compilation comp, ImmutableArray<INamedTypeSymbol?> structs) source)
        {
            var (compilation, structSymbols) = source;

            var emulatedInlineAttr = compilation.GetTypeByMetadataName("Brovan.Core.Emulation.OS.EmulatedInlineAttribute");
            var emulatedPointerAttr = compilation.GetTypeByMetadataName("Brovan.Core.Emulation.OS.EmulatedPointerAttribute");

            if (emulatedInlineAttr == null && emulatedPointerAttr == null)
                return;

            var candidates = new List<INamedTypeSymbol>();
            var seen = new HashSet<string>();

            foreach (var sym in structSymbols)
            {
                if (sym == null) continue;
                if (!seen.Add(sym.ToDisplayString())) continue;

                bool hasSpecial = false;
                foreach (var field in sym.GetMembers().OfType<IFieldSymbol>())
                {
                    foreach (var attr in field.GetAttributes())
                    {
                        if (SymbolEquals(attr.AttributeClass, emulatedInlineAttr) ||
                            SymbolEquals(attr.AttributeClass, emulatedPointerAttr))
                        {
                            hasSpecial = true;
                            break;
                        }
                    }
                    if (hasSpecial) break;
                }
                if (hasSpecial)
                    candidates.Add(sym);
            }

            if (candidates.Count == 0)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using System.Buffers.Binary;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Brovan.Core.Helpers;");
            sb.AppendLine("using static Brovan.Core.Helpers.BinaryHelpers;");
            sb.AppendLine();
            sb.AppendLine("namespace Brovan.Core.Emulation.OS");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class StructSerializer");
            sb.AppendLine("    {");

            for (int i = 0; i < candidates.Count; i++)
            {
                var sym = candidates[i];
                string typeName = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string safeName = sym.Name;

                GenerateGetSize(sb, sym, typeName, safeName, emulatedInlineAttr, emulatedPointerAttr, compilation);
                GenerateWriteStruct(sb, sym, typeName, safeName, emulatedInlineAttr, emulatedPointerAttr, compilation);
                GenerateParseStruct(sb, sym, typeName, safeName, emulatedInlineAttr, emulatedPointerAttr, compilation);

                if (i < candidates.Count - 1)
                    sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            ctx.AddSource("StructSerializer.Generated.cs", sb.ToString());
        }

        private static void GenerateGetSize(StringBuilder sb, INamedTypeSymbol sym, string typeName, string safeName,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, Compilation comp)
        {
            bool is64 = true;
            int size64 = ComputeSize(sym, true, inlineAttr, ptrAttr, comp);
            int size32 = ComputeSize(sym, false, inlineAttr, ptrAttr, comp);

            sb.AppendLine($"        public static int GetStructSizeDirect_{safeName}(bool Is64) => Is64 ? {size64} : {size32};");
        }

        private static void GenerateWriteStruct(StringBuilder sb, INamedTypeSymbol sym, string typeName, string safeName,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, Compilation comp)
        {
            sb.AppendLine($"        public static WriteStructResult WriteStructDirect_{safeName}(BinaryEmulator Emulator, ulong Address, {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine("            int Size = Is64 ? GetStructSizeDirect_" + safeName + "(true) : GetStructSizeDirect_" + safeName + "(false);");
            sb.AppendLine("            if (Size <= 0) return WriteStructResult.Fail(WriteStructError.InvalidStructLayout, \"" + safeName + " has zero size\");");
            sb.AppendLine("            if (!Emulator.IsRegionMapped(Address, (ulong)Size))");
            sb.AppendLine("                return WriteStructResult.Fail(WriteStructError.DestinationNotMapped, $\"" + safeName + " (0x{Size:X} bytes) at 0x{Address:X} is not fully mapped\");");
            sb.AppendLine("            byte[] Buf = ArrayPool<byte>.Shared.Rent(Size);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                Span<byte> Dst = Buf.AsSpan(0, Size);");
            sb.AppendLine("                Dst.Clear();");
                sb.AppendLine("                int Off = 0;");

            int offset64 = 0, offset32 = 0;
            bool isExplicit = IsExplicitLayout(sym);
            if (isExplicit)
            {
                sb.AppendLine("                int Off = Is64 ? " + offset64 + " : " + offset32 + ";");
            }

            foreach (var field in GetOrderedFields(sym, isExplicit))
            {
                string fieldName = field.Name;
                string fieldType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var (inline, ascii, ptrContent) = GetFieldAttrs(field, inlineAttr, ptrAttr);

                if (isExplicit)
                {
                    var fieldOffsetAttr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FieldOffsetAttribute");
                    int explicitOff = fieldOffsetAttr != null ? (int)fieldOffsetAttr.ConstructorArguments[0].Value! : 0;
                    sb.AppendLine($"                Off = {explicitOff};");
                    WriteFieldSerialize(sb, fieldName, fieldType, field, inline, ascii, ptrContent, "Off", comp);
                }
                else
                {
                    sb.AppendLine($"                Off = Is64 ? {offset64} : {offset32};");
                    WriteFieldSerialize(sb, fieldName, fieldType, field, inline, ascii, ptrContent, "Off", comp);
                    int sz64 = GetFieldSize(field, true, inlineAttr, ptrAttr, comp);
                    int sz32 = GetFieldSize(field, false, inlineAttr, ptrAttr, comp);
                    offset64 += sz64;
                    offset32 += sz32;
                }
            }

            sb.AppendLine("                if (!Emulator.WriteMemory(Address, Dst))");
            sb.AppendLine("                    return WriteStructResult.Fail(WriteStructError.DestinationNotMapped, $\"WriteMemory failed for " + safeName + " at 0x{Address:X}\");");
            sb.AppendLine("                return WriteStructResult.Ok;");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { ArrayPool<byte>.Shared.Return(Buf); }");
            sb.AppendLine("        }");
        }

        private static void GenerateParseStruct(StringBuilder sb, INamedTypeSymbol sym, string typeName, string safeName,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, Compilation comp)
        {
            sb.AppendLine($"        public static bool ParseStructDirect_{safeName}(BinaryEmulator Emulator, ulong Address, out {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = default;");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine("            int Size = Is64 ? GetStructSizeDirect_" + safeName + "(true) : GetStructSizeDirect_" + safeName + "(false);");
            sb.AppendLine("            if (Size <= 0) return false;");
            sb.AppendLine("            byte[] Buf = ArrayPool<byte>.Shared.Rent(Size);");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                Span<byte> Span = Buf.AsSpan(0, Size);");
            sb.AppendLine("                if (!Emulator.ReadMemory(Address, Span)) return false;");
            sb.AppendLine("                return ParseStructDirect_" + safeName + "(Emulator, Buf, out Value);");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { ArrayPool<byte>.Shared.Return(Buf); }");
            sb.AppendLine("        }");

            sb.AppendLine($"        public static bool ParseStructDirect_{safeName}(BinaryEmulator Emulator, byte[] Raw, out {typeName} Value)");
            sb.AppendLine("        {");
            sb.AppendLine("            Value = default;");
            sb.AppendLine("            bool Is64 = Emulator._binary.Architecture == BinaryArchitecture.x64;");
            sb.AppendLine("            int Off = 0;");

            int offset64 = 0, offset32 = 0;
            bool isExplicit = IsExplicitLayout(sym);

            foreach (var field in GetOrderedFields(sym, isExplicit))
            {
                string fieldName = field.Name;
                string fieldType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var (inline, ascii, ptrContent) = GetFieldAttrs(field, inlineAttr, ptrAttr);

                if (isExplicit)
                {
                    var fieldOffsetAttr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FieldOffsetAttribute");
                    int explicitOff = fieldOffsetAttr != null ? (int)fieldOffsetAttr.ConstructorArguments[0].Value! : 0;
                    sb.AppendLine($"                int Off = {explicitOff};");
                    WriteFieldDeserialize(sb, fieldName, fieldType, field, inline, ascii, ptrContent, "Off", comp);
                }
                else
                {
                    sb.AppendLine($"                Off = Is64 ? {offset64} : {offset32};");
                    WriteFieldDeserialize(sb, fieldName, fieldType, field, inline, ascii, ptrContent, "Off", comp);
                    int sz64 = GetFieldSize(field, true, inlineAttr, ptrAttr, comp);
                    int sz32 = GetFieldSize(field, false, inlineAttr, ptrAttr, comp);
                    offset64 += sz64;
                    offset32 += sz32;
                }
            }

            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
        }

        private static void WriteFieldSerialize(StringBuilder sb, string fieldName, string fieldType, IFieldSymbol field,
            int inlineSize, bool ascii, object? ptrContent, string offVar, Compilation comp)
        {
            if (field.Type.SpecialType != SpecialType.None && field.Type.SpecialType != SpecialType.System_Boolean)
            {
                WritePrimitiveSerialize(sb, fieldName, fieldType, offVar);
                return;
            }

            if (field.Type.TypeKind == TypeKind.Enum)
            {
                var underlying = ((INamedTypeSymbol)field.Type).EnumUnderlyingType!;
                WriteEnumSerialize(sb, fieldName, underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), offVar);
                return;
            }

            if (fieldType == "bool")
            {
                sb.AppendLine($"                Dst[{offVar}] = (byte)(Value.{fieldName} ? 1 : 0);");
                return;
            }

            if (fieldType == "string")
            {
                if (inlineSize > 0)
                {
                    string enc = ascii ? "Encoding.ASCII" : "Encoding.Unicode";
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    string S = Value.{fieldName} ?? \"\";");
                    sb.AppendLine($"                    byte[] Enc = {enc}.GetBytes(S);");
                    sb.AppendLine($"                    int Copy = Math.Min(Enc.Length, {inlineSize});");
                    sb.AppendLine($"                    Enc.AsSpan(0, Copy).CopyTo(Dst.Slice({offVar}, Copy));");
                    sb.AppendLine($"                }}");
                }
                else if (ptrContent != null)
                {
                    bool isAscii = ptrContent.ToString() == "AsciiString";
                    string enc = isAscii ? "Encoding.ASCII" : "Encoding.Unicode";
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    ulong StrPtr = 0;");
                    sb.AppendLine($"                    string? S = Value.{fieldName};");
                    sb.AppendLine($"                    if (S != null)");
                    sb.AppendLine($"                    {{");
                    sb.AppendLine($"                        byte[] Enc = {enc}.GetBytes(S);");
                    sb.AppendLine($"                        byte[] Full = new byte[Enc.Length + ({(isAscii ? "1" : "2")})];");
                    sb.AppendLine($"                        Buffer.BlockCopy(Enc, 0, Full, 0, Enc.Length);");
                    sb.AppendLine($"                        StrPtr = Emulator.MapUniqueAddress((ulong)Full.Length, MemoryProtection.ReadWrite);");
                    sb.AppendLine($"                        if (StrPtr == 0) return WriteStructResult.Fail(WriteStructError.StringAllocationFailed, $\"Alloc failed for {fieldName}\");");
                    sb.AppendLine($"                        if (!Emulator.WriteMemory(StrPtr, Full)) return WriteStructResult.Fail(WriteStructError.PointerDestinationNotMapped, $\"WriteMemory failed for {fieldName}\");");
                    sb.AppendLine($"                    }}");
                    sb.AppendLine($"                    if (Is64) BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), StrPtr);");
                    sb.AppendLine($"                    else BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), (uint)StrPtr);");
                    sb.AppendLine($"                }}");
                }
                return;
            }

            if (fieldType == "byte[]")
            {
                if (inlineSize > 0)
                {
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    byte[]? Src = Value.{fieldName};");
                    sb.AppendLine($"                    if (Src != null) {{ int Copy = Math.Min(Src.Length, {inlineSize}); Src.AsSpan(0, Copy).CopyTo(Dst.Slice({offVar}, Copy)); }}");
                    sb.AppendLine($"                }}");
                }
                else
                {
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    ulong BytePtr = 0;");
                    sb.AppendLine($"                    byte[]? RawB = Value.{fieldName};");
                    sb.AppendLine($"                    if (RawB != null && RawB.Length > 0)");
                    sb.AppendLine($"                    {{");
                    sb.AppendLine($"                        BytePtr = Emulator.MapUniqueAddress((ulong)RawB.Length, MemoryProtection.ReadWrite);");
                    sb.AppendLine($"                        if (BytePtr == 0) return WriteStructResult.Fail(WriteStructError.PointerAllocationFailed, $\"Alloc failed for {fieldName}\");");
                    sb.AppendLine($"                        if (!Emulator.WriteMemory(BytePtr, RawB)) return WriteStructResult.Fail(WriteStructError.PointerDestinationNotMapped, $\"WriteMemory failed for {fieldName}\");");
                    sb.AppendLine($"                    }}");
                    sb.AppendLine($"                    if (Is64) BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), BytePtr);");
                    sb.AppendLine($"                    else BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), (uint)BytePtr);");
                    sb.AppendLine($"                }}");
                }
                return;
            }

            if (field.Type.IsValueType && !IsPrimitiveType(field.Type))
            {
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    {fieldType} Nested = Value.{fieldName};");
                sb.AppendLine($"                    int NestedSize = Is64 ? GetStructSizeDirect_{((INamedTypeSymbol)field.Type).Name}(true) : GetStructSizeDirect_{((INamedTypeSymbol)field.Type).Name}(false);");
                sb.AppendLine($"                    Span<byte> NestedSpan = Dst.Slice({offVar}, NestedSize);");
                sb.AppendLine($"                    if (!WriteStructNested_{((INamedTypeSymbol)field.Type).Name}(NestedSpan, Nested, Is64))");
                sb.AppendLine($"                        return WriteStructResult.Fail(WriteStructError.UnsupportedFieldType, $\"Failed to serialize nested {fieldName}\");");
                sb.AppendLine($"                }}");
                return;
            }
        }

        private static void WriteFieldDeserialize(StringBuilder sb, string fieldName, string fieldType, IFieldSymbol field,
            int inlineSize, bool ascii, object? ptrContent, string offVar, Compilation comp)
        {
            if (field.Type.SpecialType != SpecialType.None && field.Type.SpecialType != SpecialType.System_Boolean)
            {
                WritePrimitiveDeserialize(sb, fieldName, fieldType, offVar);
                return;
            }

            if (field.Type.TypeKind == TypeKind.Enum)
            {
                var underlying = ((INamedTypeSymbol)field.Type).EnumUnderlyingType!;
                WriteEnumDeserialize(sb, fieldName, fieldType, underlying.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), offVar);
                return;
            }

            if (fieldType == "bool")
            {
                sb.AppendLine($"                Value.{fieldName} = Raw[{offVar}] != 0;");
                return;
            }

            if (fieldType == "string")
            {
                if (inlineSize > 0)
                {
                    string enc = ascii ? "Encoding.ASCII" : "Encoding.Unicode";
                    int step = ascii ? 1 : 2;
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    int Len = {inlineSize};");
                    sb.AppendLine($"                    while (Len >= {step} && Raw[{offVar} + Len - {step}] == 0{(step == 2 ? " && Raw[" + offVar + " + Len - 1] == 0" : "")}) Len -= {step};");
                    sb.AppendLine($"                    Value.{fieldName} = {enc}.GetString(Raw, {offVar}, Len);");
                    sb.AppendLine($"                }}");
                }
                else if (ptrContent != null)
                {
                    bool isAscii = ptrContent.ToString() == "AsciiString";
                    string enc = isAscii ? "Encoding.ASCII" : "Encoding.Unicode";
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    ulong StrP = Is64 ? BitConverter.ToUInt64(Raw, {offVar}) : BitConverter.ToUInt32(Raw, {offVar});");
                    sb.AppendLine($"                    Value.{fieldName} = StrP != 0 ? ReadNullTerminatedString(Emulator, StrP, {enc}) : null;");
                    sb.AppendLine($"                }}");
                }
                return;
            }

            if (fieldType == "byte[]")
            {
                if (inlineSize > 0)
                {
                    sb.AppendLine($"                    {{ byte[] Inline = new byte[{inlineSize}]; Buffer.BlockCopy(Raw, {offVar}, Inline, 0, {inlineSize}); Value.{fieldName} = Inline; }}");
                }
                return;
            }
        }

        private static void WritePrimitiveSerialize(StringBuilder sb, string fieldName, string fieldType, string offVar)
        {
            switch (fieldType)
            {
                case "byte": sb.AppendLine($"                Dst[{offVar}] = Value.{fieldName};"); break;
                case "sbyte": sb.AppendLine($"                Dst[{offVar}] = (byte)Value.{fieldName};"); break;
                case "ushort": sb.AppendLine($"                BinaryPrimitives.WriteUInt16LittleEndian(Dst.Slice({offVar}, 2), Value.{fieldName});"); break;
                case "short": sb.AppendLine($"                BinaryPrimitives.WriteInt16LittleEndian(Dst.Slice({offVar}, 2), Value.{fieldName});"); break;
                case "uint": sb.AppendLine($"                BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), Value.{fieldName});"); break;
                case "int": sb.AppendLine($"                BinaryPrimitives.WriteInt32LittleEndian(Dst.Slice({offVar}, 4), Value.{fieldName});"); break;
                case "ulong": sb.AppendLine($"                BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), Value.{fieldName};"); break;
                case "long": sb.AppendLine($"                BinaryPrimitives.WriteInt64LittleEndian(Dst.Slice({offVar}, 8), Value.{fieldName});"); break;
                case "float": sb.AppendLine($"                BinaryPrimitives.WriteSingleLittleEndian(Dst.Slice({offVar}, 4), Value.{fieldName});"); break;
                case "double": sb.AppendLine($"                BinaryPrimitives.WriteDoubleLittleEndian(Dst.Slice({offVar}, 8), Value.{fieldName});"); break;
                default: sb.AppendLine($"                // Unsupported: {fieldType} {fieldName}"); break;
            }
        }

        private static void WritePrimitiveDeserialize(StringBuilder sb, string fieldName, string fieldType, string offVar)
        {
            switch (fieldType)
            {
                case "byte": sb.AppendLine($"                Value.{fieldName} = Raw[{offVar}];"); break;
                case "sbyte": sb.AppendLine($"                Value.{fieldName} = (sbyte)Raw[{offVar}];"); break;
                case "ushort": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToUInt16(Raw, {offVar});"); break;
                case "short": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToInt16(Raw, {offVar});"); break;
                case "uint": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToUInt32(Raw, {offVar});"); break;
                case "int": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToInt32(Raw, {offVar});"); break;
                case "ulong": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToUInt64(Raw, {offVar});"); break;
                case "long": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToInt64(Raw, {offVar});"); break;
                case "float": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToSingle(Raw, {offVar});"); break;
                case "double": sb.AppendLine($"                Value.{fieldName} = BitConverter.ToDouble(Raw, {offVar});"); break;
                default: sb.AppendLine($"                // Unsupported: {fieldType} {fieldName}"); break;
            }
        }

        private static void WriteEnumSerialize(StringBuilder sb, string fieldName, string underlying, string offVar)
        {
            if (underlying == "byte") sb.AppendLine($"                Dst[{offVar}] = (byte)Value.{fieldName};");
            else if (underlying == "sbyte") sb.AppendLine($"                Dst[{offVar}] = (byte)Value.{fieldName};");
            else if (underlying == "ushort") sb.AppendLine($"                BinaryPrimitives.WriteUInt16LittleEndian(Dst.Slice({offVar}, 2), (ushort)Value.{fieldName});");
            else if (underlying == "short") sb.AppendLine($"                BinaryPrimitives.WriteInt16LittleEndian(Dst.Slice({offVar}, 2), (short)Value.{fieldName});");
            else if (underlying == "uint") sb.AppendLine($"                BinaryPrimitives.WriteUInt32LittleEndian(Dst.Slice({offVar}, 4), (uint)Value.{fieldName});");
            else if (underlying == "int") sb.AppendLine($"                BinaryPrimitives.WriteInt32LittleEndian(Dst.Slice({offVar}, 4), (int)Value.{fieldName};");
            else if (underlying == "ulong") sb.AppendLine($"                BinaryPrimitives.WriteUInt64LittleEndian(Dst.Slice({offVar}, 8), (ulong)Value.{fieldName};");
            else if (underlying == "long") sb.AppendLine($"                BinaryPrimitives.WriteInt64LittleEndian(Dst.Slice({offVar}, 8), (long)Value.{fieldName});");
        }

        private static void WriteEnumDeserialize(StringBuilder sb, string fieldName, string fieldType, string underlying, string offVar)
        {
            if (underlying == "byte") sb.AppendLine($"                Value.{fieldName} = ({fieldType})Raw[{offVar}];");
            else if (underlying == "sbyte") sb.AppendLine($"                Value.{fieldName} = ({fieldType})(sbyte)Raw[{offVar}];");
            else if (underlying == "ushort") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToUInt16(Raw, {offVar});");
            else if (underlying == "short") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToInt16(Raw, {offVar});");
            else if (underlying == "uint") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToUInt32(Raw, {offVar});");
            else if (underlying == "int") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToInt32(Raw, {offVar});");
            else if (underlying == "ulong") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToUInt64(Raw, {offVar});");
            else if (underlying == "long") sb.AppendLine($"                Value.{fieldName} = ({fieldType})BitConverter.ToInt64(Raw, {offVar});");
        }

        private static bool IsExplicitLayout(INamedTypeSymbol sym)
        {
            return sym.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.StructLayoutAttribute" &&
                a.ConstructorArguments.Length > 0 &&
                a.ConstructorArguments[0].Value?.ToString() == "Explicit");
        }

        private static IEnumerable<IFieldSymbol> GetOrderedFields(INamedTypeSymbol sym, bool isExplicit)
        {
            var fields = sym.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic).ToList();
            if (isExplicit)
            {
                fields = fields.OrderBy(f =>
                {
                    var attr = f.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FieldOffsetAttribute");
                    return attr != null ? (int)attr.ConstructorArguments[0].Value! : 0;
                }).ToList();
            }
            return fields;
        }

        private static (int inlineSize, bool ascii, object? ptrContent) GetFieldAttrs(IFieldSymbol field,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr)
        {
            int inlineSize = 0;
            bool ascii = false;
            object? ptrContent = null;

            foreach (var attr in field.GetAttributes())
            {
                if (SymbolEquals(attr.AttributeClass, inlineAttr) && attr.ConstructorArguments.Length > 0)
                {
                    inlineSize = (int)attr.ConstructorArguments[0].Value!;
                    foreach (var na in attr.NamedArguments)
                    {
                        if (na.Key == "Ascii" && na.Value.Value is bool b)
                            ascii = b;
                    }
                }
                if (SymbolEquals(attr.AttributeClass, ptrAttr) && attr.ConstructorArguments.Length > 0)
                {
                    ptrContent = attr.ConstructorArguments[0].Value;
                }
            }

            return (inlineSize, ascii, ptrContent);
        }

        private static int ComputeSize(INamedTypeSymbol sym, bool is64,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, Compilation comp)
        {
            bool isExplicit = IsExplicitLayout(sym);
            int max = 0;

            foreach (var field in GetOrderedFields(sym, isExplicit))
            {
                int fieldOffset = 0;
                if (isExplicit)
                {
                    var fieldOffsetAttr = field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == "FieldOffsetAttribute");
                    fieldOffset = fieldOffsetAttr != null ? (int)fieldOffsetAttr.ConstructorArguments[0].Value! : 0;
                }

                int sz = GetFieldSize(field, is64, inlineAttr, ptrAttr, comp);
                max = Math.Max(max, fieldOffset + sz);
            }

            return max;
        }

        private static int GetFieldSize(IFieldSymbol field, bool is64,
            INamedTypeSymbol? inlineAttr, INamedTypeSymbol? ptrAttr, Compilation comp)
        {
            var (inlineSize, _, _) = GetFieldAttrs(field, inlineAttr, ptrAttr);

            var ft = field.Type;
            if (ft.TypeKind == TypeKind.Enum)
                ft = ((INamedTypeSymbol)ft).EnumUnderlyingType!;

            switch (ft.SpecialType)
            {
                case SpecialType.System_Boolean: return 1;
                case SpecialType.System_Byte: return 1;
                case SpecialType.System_SByte: return 1;
                case SpecialType.System_Int16: return 2;
                case SpecialType.System_UInt16: return 2;
                case SpecialType.System_Int32: return 4;
                case SpecialType.System_UInt32: return 4;
                case SpecialType.System_Int64: return 8;
                case SpecialType.System_UInt64: return 8;
                case SpecialType.System_Single: return 4;
                case SpecialType.System_Double: return 8;
            }

            if (ft.ToDisplayString() == "string" || ft.ToDisplayString() == "byte[]")
            {
                if (inlineSize > 0) return inlineSize;
                return is64 ? 8 : 4;
            }

            if (ft.IsValueType && !IsPrimitiveType(ft))
            {
                return ComputeSize((INamedTypeSymbol)ft, is64, inlineAttr, ptrAttr, comp);
            }

            return 0;
        }

        private static bool IsPrimitiveType(ITypeSymbol t)
        {
            switch (t.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_Byte:
                case SpecialType.System_SByte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                    return true;
                default:
                    return false;
            }
        }

        private static bool SymbolEquals(ISymbol? a, ISymbol? b)
        {
            if (a == null || b == null) return false;
            return SymbolEqualityComparer.Default.Equals(a, b);
        }
    }
}
